version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: waf_redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  responder:
    build: ./responder
    container_name: waf_responder
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  detection:
    build: ./detection
    container_name: waf_detection
    ports:
      - "5000:5000"
    environment:
      # detection 서비스에 Responder의 주소를 알려줍니다.
      - RESPONDER_URL=http://responder:8000/block
