version: '3.8'

services:
  responder:
    build: ./responder
    image: waf-responder:latest # 빌드 후 생성될 이미지 이름 명시

  detection:
    build: ./detection
    image: waf-detection:latest # 빌드 후 생성될 이미지 이름 명시